/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loteria;

import java.awt.Color;
import java.util.Stack;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PC T-REX
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon img[] = new ImageIcon[117];
        int pos;
        int nCartas = 16;
        int[] numeros = new int[17];
        Stack< Integer> pCartas = new Stack< Integer>();
        for (int i = 0; i < nCartas; i++) {
            pos = (int) Math.floor(Math.random() * nCartas);
            while (pCartas.contains(pos)) {
                pos = (int) Math.floor(Math.random() * nCartas);
            }
            pCartas.push(pos);
        }
        
        for (int i = 0; i < 16; i++) {
            
            numeros[i] = pCartas.get(i);
        }

        uno.setHorizontalAlignment(uno.CENTER);
        uno.setVerticalAlignment(uno.CENTER);
        dos.setHorizontalAlignment(dos.CENTER);
        dos.setVerticalAlignment(dos.CENTER);
        tres.setHorizontalAlignment(tres.CENTER);
        tres.setVerticalAlignment(tres.CENTER);
        cuatro.setHorizontalAlignment(cuatro.CENTER);
        cuatro.setVerticalAlignment(cuatro.CENTER);
        cinco.setHorizontalAlignment(cinco.CENTER);
        cinco.setVerticalAlignment(cinco.CENTER);
        seis.setHorizontalAlignment(seis.CENTER);
        seis.setVerticalAlignment(seis.CENTER);
        siete.setHorizontalAlignment(siete.CENTER);
        siete.setVerticalAlignment(siete.CENTER);
        ocho.setHorizontalAlignment(ocho.CENTER);
        ocho.setVerticalAlignment(ocho.CENTER);
        nueve.setHorizontalAlignment(nueve.CENTER);
        nueve.setVerticalAlignment(nueve.CENTER);
        diez.setHorizontalAlignment(diez.CENTER);
        diez.setVerticalAlignment(diez.CENTER);
        once.setHorizontalAlignment(once.CENTER);
        once.setVerticalAlignment(once.CENTER);
        doce.setHorizontalAlignment(doce.CENTER);
        doce.setVerticalAlignment(doce.CENTER);
        trece.setHorizontalAlignment(trece.CENTER);
        trece.setVerticalAlignment(trece.CENTER);
        catorce.setHorizontalAlignment(catorce.CENTER);
        catorce.setVerticalAlignment(catorce.CENTER);
        quince.setHorizontalAlignment(quince.CENTER);
        quince.setVerticalAlignment(quince.CENTER);
        dieciseis.setHorizontalAlignment(dieciseis.CENTER);
        dieciseis.setVerticalAlignment(dieciseis.CENTER);
        for (int i = 0; i < 17; i++) {
            img[i] = new ImageIcon(getClass().getClassLoader().getResource("imagenes/" + numeros[i] + ".png"));
        }
        //img[1] = new ImageIcon(getClass().getClassLoader().getResource("imagenes/1.png"));
        uno.setIcon(img[0]);
        dos.setIcon(img[1]);
        tres.setIcon(img[2]);
        cuatro.setIcon(img[3]);
        cinco.setIcon(img[4]);
        seis.setIcon(img[5]);
        siete.setIcon(img[6]);
        ocho.setIcon(img[7]);
        nueve.setIcon(img[8]);
        diez.setIcon(img[9]);
        once.setIcon(img[10]);
        doce.setIcon(img[11]);
        trece.setIcon(img[12]);
        catorce.setIcon(img[13]);
        quince.setIcon(img[14]);
        dieciseis.setIcon(img[15]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uno = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cinco = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        ocho = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nueve = new javax.swing.JLabel();
        diez = new javax.swing.JLabel();
        once = new javax.swing.JLabel();
        doce = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        trece = new javax.swing.JLabel();
        catorce = new javax.swing.JLabel();
        quince = new javax.swing.JLabel();
        dieciseis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        uno.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        uno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unoMouseClicked(evt);
            }
        });
        jPanel1.add(uno);

        dos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosMouseClicked(evt);
            }
        });
        jPanel1.add(dos);

        tres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresMouseClicked(evt);
            }
        });
        jPanel1.add(tres);

        cuatro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuatroMouseClicked(evt);
            }
        });
        jPanel1.add(cuatro);

        jPanel2.setLayout(new java.awt.GridLayout());

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/5.png"))); // NOI18N
        cinco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });
        jPanel2.add(cinco);

        seis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seisMouseClicked(evt);
            }
        });
        jPanel2.add(seis);

        siete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        siete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sieteMouseClicked(evt);
            }
        });
        jPanel2.add(siete);

        ocho.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ocho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ochoMouseClicked(evt);
            }
        });
        jPanel2.add(ocho);

        jPanel3.setLayout(new java.awt.GridLayout());

        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9.png"))); // NOI18N
        nueve.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nueveMouseClicked(evt);
            }
        });
        jPanel3.add(nueve);

        diez.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        diez.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diezMouseClicked(evt);
            }
        });
        jPanel3.add(diez);

        once.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        once.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        once.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onceMouseClicked(evt);
            }
        });
        jPanel3.add(once);

        doce.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        doce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doceMouseClicked(evt);
            }
        });
        jPanel3.add(doce);

        jPanel4.setLayout(new java.awt.GridLayout());

        trece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/13.png"))); // NOI18N
        trece.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        trece.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trece.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treceMouseClicked(evt);
            }
        });
        jPanel4.add(trece);

        catorce.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        catorce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catorce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catorceMouseClicked(evt);
            }
        });
        jPanel4.add(catorce);

        quince.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        quince.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quince.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quinceMouseClicked(evt);
            }
        });
        jPanel4.add(quince);

        dieciseis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dieciseis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dieciseis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dieciseisMouseClicked(evt);
            }
        });
        jPanel4.add(dieciseis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMouseClicked
        // TODO add your handling code here:
        // ImageIcon iconLogo = new ImageIcon("/imagenes/gallo.jpg");
        //  uno.setIcon(iconLogo);

        uno.enable(false);
        //uno.setIcon(null);
        uno.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }

        }

    }//GEN-LAST:event_unoMouseClicked

    private void dosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMouseClicked
        // TODO add your handling code here:
        dos.enable(false);
        //dos.setIcon(null);
        dos.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_dosMouseClicked

    private void tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseClicked
        // TODO add your handling code here:
        tres.enable(false);
        //tres.setIcon(null);
        tres.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_tresMouseClicked

    private void cuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMouseClicked
        // TODO add your handling code here:
        cuatro.enable(false);
        //cuatro.setIcon(null);
        cuatro.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_cuatroMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        // TODO add your handling code here:
        cinco.enable(false);
        //cuatro.setIcon(null);
        cinco.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_cincoMouseClicked

    private void seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseClicked
        // TODO add your handling code here:
        seis.enable(false);
        //cuatro.setIcon(null);
        seis.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_seisMouseClicked

    private void sieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMouseClicked
        // TODO add your handling code here:
        siete.enable(false);
        //cuatro.setIcon(null);
        siete.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_sieteMouseClicked

    private void ochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMouseClicked
        // TODO add your handling code here:
        ocho.enable(false);
        //cuatro.setIcon(null);
        ocho.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_ochoMouseClicked

    private void nueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMouseClicked
        // TODO add your handling code here:
        nueve.enable(false);
        //cuatro.setIcon(null);
        nueve.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_nueveMouseClicked

    private void diezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diezMouseClicked
        // TODO add your handling code here:
        diez.enable(false);
        //cuatro.setIcon(null);
        diez.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_diezMouseClicked

    private void onceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onceMouseClicked
        // TODO add your handling code here:
        once.enable(false);
        //cuatro.setIcon(null);
        once.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_onceMouseClicked

    private void doceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doceMouseClicked
        // TODO add your handling code here:
        doce.enable(false);
        //cuatro.setIcon(null);
        doce.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_doceMouseClicked

    private void treceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treceMouseClicked
        // TODO add your handling code here:
        trece.enable(false);
        //cuatro.setIcon(null);
        trece.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_treceMouseClicked

    private void catorceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catorceMouseClicked
        // TODO add your handling code here:
        catorce.enable(false);
        //cuatro.setIcon(null);
        catorce.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_catorceMouseClicked

    private void quinceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quinceMouseClicked
        // TODO add your handling code here:
        quince.enable(false);
        //cuatro.setIcon(null);
        quince.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_quinceMouseClicked

    private void dieciseisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dieciseisMouseClicked
        // TODO add your handling code here:
        dieciseis.enable(false);
        //cuatro.setIcon(null);
        dieciseis.setBackground(new Color(0,0,0,1));
        if(uno.isEnabled()==false && dos.isEnabled()==false && tres.isEnabled()==false && cuatro.isEnabled()==false &&
            cinco.isEnabled()==false && seis.isEnabled()==false && siete.isEnabled()==false && ocho.isEnabled()==false &&
            nueve.isEnabled()==false && diez.isEnabled()==false && once.isEnabled()==false && doce.isEnabled()==false &&
            trece.isEnabled()==false && catorce.isEnabled()==false && quince.isEnabled()==false && dieciseis.isEnabled()==false){
            JOptionPane.showMessageDialog(null, "¡Lotería!");
            int result = JOptionPane.showConfirmDialog(this,"¿Quieres volver a jugar?", "Fin del juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dispose();
                Tablero nF = new Tablero();
                nF.setVisible(true);
            }else if (result == JOptionPane.NO_OPTION){
                System.exit(0);
            }else {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_dieciseisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catorce;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel dieciseis;
    private javax.swing.JLabel diez;
    private javax.swing.JLabel doce;
    private javax.swing.JLabel dos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nueve;
    private javax.swing.JLabel ocho;
    private javax.swing.JLabel once;
    private javax.swing.JLabel quince;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel trece;
    private javax.swing.JLabel tres;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
